project:
  type: website
  output-dir: docs

website:
  title: "Hussein Mahfouz"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: CV/CV_Hussein_Mahfouz.pdf
        text: CV
      - icon: github
        href: https://github.com/Hussein-Mahfouz
      - icon: twitter
        href: https://twitter.com/h_mahfouz
format:
  html:
    theme: flatly
    css: styles.css
    #toc: true

editor: visual

